export const SUCCESS = "SUCCESS";

export const FAILURE = "FAILURE";

export const REDIRECT_MESSAGE = "REDIRECT_MESSAGE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADD_PROFILE = "ADD_PROFILE";

export const ADD_DATATABLE = "ADD_DATATABLE";

export const REMOVE_PROFILE = "REMOVE_PROFILE";

export const OPEN_SIDEBAR = "OPEN_SIDEBAR";

export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR"
